/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RentRouteImport } from './routes/rent'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppOrganizationsRouteImport } from './routes/app/organizations'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppTransactionsRouteRouteImport } from './routes/app/transactions/route'
import { Route as AppSellersRouteRouteImport } from './routes/app/sellers/route'
import { Route as AppReportsRouteRouteImport } from './routes/app/reports/route'
import { Route as AppPropertiesRouteRouteImport } from './routes/app/properties/route'
import { Route as AppLeadsRouteRouteImport } from './routes/app/leads/route'
import { Route as AppDocumentsRouteRouteImport } from './routes/app/documents/route'
import { Route as AppBuyersRouteRouteImport } from './routes/app/buyers/route'
import { Route as AppTransactionsIndexRouteImport } from './routes/app/transactions/index'
import { Route as AppSellersIndexRouteImport } from './routes/app/sellers/index'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports/index'
import { Route as AppPropertiesIndexRouteImport } from './routes/app/properties/index'
import { Route as AppLeadsIndexRouteImport } from './routes/app/leads/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppBuyersIndexRouteImport } from './routes/app/buyers/index'
import { Route as AppTransactionsNewRouteImport } from './routes/app/transactions/new'
import { Route as AppTransactionsTransactionIdRouteImport } from './routes/app/transactions/$transactionId'
import { Route as AppSellersNewRouteImport } from './routes/app/sellers/new'
import { Route as AppSellersSellerIdRouteImport } from './routes/app/sellers/$sellerId'
import { Route as AppReportsSimulatorRouteImport } from './routes/app/reports/simulator'
import { Route as AppReportsAiRouteImport } from './routes/app/reports/ai'
import { Route as AppPropertiesPropertyIdRouteImport } from './routes/app/properties/$propertyId'
import { Route as AppLeadsNewRouteImport } from './routes/app/leads/new'
import { Route as AppLeadsLeadIdRouteImport } from './routes/app/leads/$leadId'
import { Route as AppDocumentsNewRouteImport } from './routes/app/documents/new'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/app/documents/$documentId'
import { Route as AppBuyersNewRouteImport } from './routes/app/buyers/new'
import { Route as AppBuyersBuyerIdRouteImport } from './routes/app/buyers/$buyerId'

const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRouteRoute = AppTransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSellersRouteRoute = AppSellersRouteRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRouteRoute = AppReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRouteRoute = AppPropertiesRouteRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRouteRoute = AppLeadsRouteRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRouteRoute = AppDocumentsRouteRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyersRouteRoute = AppBuyersRouteRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTransactionsRouteRoute,
} as any)
const AppSellersIndexRoute = AppSellersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSellersRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRouteRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropertiesRouteRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRouteRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsRouteRoute,
} as any)
const AppBuyersIndexRoute = AppBuyersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBuyersRouteRoute,
} as any)
const AppTransactionsNewRoute = AppTransactionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTransactionsRouteRoute,
} as any)
const AppTransactionsTransactionIdRoute =
  AppTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AppTransactionsRouteRoute,
  } as any)
const AppSellersNewRoute = AppSellersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSellersRouteRoute,
} as any)
const AppSellersSellerIdRoute = AppSellersSellerIdRouteImport.update({
  id: '/$sellerId',
  path: '/$sellerId',
  getParentRoute: () => AppSellersRouteRoute,
} as any)
const AppReportsSimulatorRoute = AppReportsSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppReportsRouteRoute,
} as any)
const AppReportsAiRoute = AppReportsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppReportsRouteRoute,
} as any)
const AppPropertiesPropertyIdRoute = AppPropertiesPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => AppPropertiesRouteRoute,
} as any)
const AppLeadsNewRoute = AppLeadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLeadsRouteRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRouteRoute,
} as any)
const AppDocumentsNewRoute = AppDocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDocumentsRouteRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => AppDocumentsRouteRoute,
} as any)
const AppBuyersNewRoute = AppBuyersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppBuyersRouteRoute,
} as any)
const AppBuyersBuyerIdRoute = AppBuyersBuyerIdRouteImport.update({
  id: '/$buyerId',
  path: '/$buyerId',
  getParentRoute: () => AppBuyersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/buy': typeof BuyRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/rent': typeof RentRoute
  '/sell': typeof SellRoute
  '/app/buyers': typeof AppBuyersRouteRouteWithChildren
  '/app/documents': typeof AppDocumentsRouteRouteWithChildren
  '/app/leads': typeof AppLeadsRouteRouteWithChildren
  '/app/properties': typeof AppPropertiesRouteRouteWithChildren
  '/app/reports': typeof AppReportsRouteRouteWithChildren
  '/app/sellers': typeof AppSellersRouteRouteWithChildren
  '/app/transactions': typeof AppTransactionsRouteRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/buyers/$buyerId': typeof AppBuyersBuyerIdRoute
  '/app/buyers/new': typeof AppBuyersNewRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/new': typeof AppDocumentsNewRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads/new': typeof AppLeadsNewRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/app/reports/ai': typeof AppReportsAiRoute
  '/app/reports/simulator': typeof AppReportsSimulatorRoute
  '/app/sellers/$sellerId': typeof AppSellersSellerIdRoute
  '/app/sellers/new': typeof AppSellersNewRoute
  '/app/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/app/transactions/new': typeof AppTransactionsNewRoute
  '/app/buyers/': typeof AppBuyersIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/sellers/': typeof AppSellersIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/buy': typeof BuyRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/rent': typeof RentRoute
  '/sell': typeof SellRoute
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/buyers/$buyerId': typeof AppBuyersBuyerIdRoute
  '/app/buyers/new': typeof AppBuyersNewRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/new': typeof AppDocumentsNewRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads/new': typeof AppLeadsNewRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/app/reports/ai': typeof AppReportsAiRoute
  '/app/reports/simulator': typeof AppReportsSimulatorRoute
  '/app/sellers/$sellerId': typeof AppSellersSellerIdRoute
  '/app/sellers/new': typeof AppSellersNewRoute
  '/app/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/app/transactions/new': typeof AppTransactionsNewRoute
  '/app/buyers': typeof AppBuyersIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/leads': typeof AppLeadsIndexRoute
  '/app/properties': typeof AppPropertiesIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/sellers': typeof AppSellersIndexRoute
  '/app/transactions': typeof AppTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/buy': typeof BuyRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/rent': typeof RentRoute
  '/sell': typeof SellRoute
  '/app/buyers': typeof AppBuyersRouteRouteWithChildren
  '/app/documents': typeof AppDocumentsRouteRouteWithChildren
  '/app/leads': typeof AppLeadsRouteRouteWithChildren
  '/app/properties': typeof AppPropertiesRouteRouteWithChildren
  '/app/reports': typeof AppReportsRouteRouteWithChildren
  '/app/sellers': typeof AppSellersRouteRouteWithChildren
  '/app/transactions': typeof AppTransactionsRouteRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/buyers/$buyerId': typeof AppBuyersBuyerIdRoute
  '/app/buyers/new': typeof AppBuyersNewRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/new': typeof AppDocumentsNewRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads/new': typeof AppLeadsNewRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/app/reports/ai': typeof AppReportsAiRoute
  '/app/reports/simulator': typeof AppReportsSimulatorRoute
  '/app/sellers/$sellerId': typeof AppSellersSellerIdRoute
  '/app/sellers/new': typeof AppSellersNewRoute
  '/app/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/app/transactions/new': typeof AppTransactionsNewRoute
  '/app/buyers/': typeof AppBuyersIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/sellers/': typeof AppSellersIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/buy'
    | '/demo'
    | '/login'
    | '/properties'
    | '/rent'
    | '/sell'
    | '/app/buyers'
    | '/app/documents'
    | '/app/leads'
    | '/app/properties'
    | '/app/reports'
    | '/app/sellers'
    | '/app/transactions'
    | '/app/admin'
    | '/app/billing'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/organizations'
    | '/app/settings'
    | '/app/tasks'
    | '/app/buyers/$buyerId'
    | '/app/buyers/new'
    | '/app/documents/$documentId'
    | '/app/documents/new'
    | '/app/leads/$leadId'
    | '/app/leads/new'
    | '/app/properties/$propertyId'
    | '/app/reports/ai'
    | '/app/reports/simulator'
    | '/app/sellers/$sellerId'
    | '/app/sellers/new'
    | '/app/transactions/$transactionId'
    | '/app/transactions/new'
    | '/app/buyers/'
    | '/app/documents/'
    | '/app/leads/'
    | '/app/properties/'
    | '/app/reports/'
    | '/app/sellers/'
    | '/app/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/buy'
    | '/demo'
    | '/login'
    | '/properties'
    | '/rent'
    | '/sell'
    | '/app/admin'
    | '/app/billing'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/organizations'
    | '/app/settings'
    | '/app/tasks'
    | '/app/buyers/$buyerId'
    | '/app/buyers/new'
    | '/app/documents/$documentId'
    | '/app/documents/new'
    | '/app/leads/$leadId'
    | '/app/leads/new'
    | '/app/properties/$propertyId'
    | '/app/reports/ai'
    | '/app/reports/simulator'
    | '/app/sellers/$sellerId'
    | '/app/sellers/new'
    | '/app/transactions/$transactionId'
    | '/app/transactions/new'
    | '/app/buyers'
    | '/app/documents'
    | '/app/leads'
    | '/app/properties'
    | '/app/reports'
    | '/app/sellers'
    | '/app/transactions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/buy'
    | '/demo'
    | '/login'
    | '/properties'
    | '/rent'
    | '/sell'
    | '/app/buyers'
    | '/app/documents'
    | '/app/leads'
    | '/app/properties'
    | '/app/reports'
    | '/app/sellers'
    | '/app/transactions'
    | '/app/admin'
    | '/app/billing'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/organizations'
    | '/app/settings'
    | '/app/tasks'
    | '/app/buyers/$buyerId'
    | '/app/buyers/new'
    | '/app/documents/$documentId'
    | '/app/documents/new'
    | '/app/leads/$leadId'
    | '/app/leads/new'
    | '/app/properties/$propertyId'
    | '/app/reports/ai'
    | '/app/reports/simulator'
    | '/app/sellers/$sellerId'
    | '/app/sellers/new'
    | '/app/transactions/$transactionId'
    | '/app/transactions/new'
    | '/app/buyers/'
    | '/app/documents/'
    | '/app/leads/'
    | '/app/properties/'
    | '/app/reports/'
    | '/app/sellers/'
    | '/app/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BuyRoute: typeof BuyRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PropertiesRoute: typeof PropertiesRoute
  RentRoute: typeof RentRoute
  SellRoute: typeof SellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations': {
      id: '/app/organizations'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sellers': {
      id: '/app/sellers'
      path: '/sellers'
      fullPath: '/app/sellers'
      preLoaderRoute: typeof AppSellersRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyers': {
      id: '/app/buyers'
      path: '/buyers'
      fullPath: '/app/buyers'
      preLoaderRoute: typeof AppBuyersRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/': {
      id: '/app/transactions/'
      path: '/'
      fullPath: '/app/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppTransactionsRouteRoute
    }
    '/app/sellers/': {
      id: '/app/sellers/'
      path: '/'
      fullPath: '/app/sellers/'
      preLoaderRoute: typeof AppSellersIndexRouteImport
      parentRoute: typeof AppSellersRouteRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRouteRoute
    }
    '/app/properties/': {
      id: '/app/properties/'
      path: '/'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppPropertiesRouteRoute
    }
    '/app/leads/': {
      id: '/app/leads/'
      path: '/'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRouteRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppDocumentsRouteRoute
    }
    '/app/buyers/': {
      id: '/app/buyers/'
      path: '/'
      fullPath: '/app/buyers/'
      preLoaderRoute: typeof AppBuyersIndexRouteImport
      parentRoute: typeof AppBuyersRouteRoute
    }
    '/app/transactions/new': {
      id: '/app/transactions/new'
      path: '/new'
      fullPath: '/app/transactions/new'
      preLoaderRoute: typeof AppTransactionsNewRouteImport
      parentRoute: typeof AppTransactionsRouteRoute
    }
    '/app/transactions/$transactionId': {
      id: '/app/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/app/transactions/$transactionId'
      preLoaderRoute: typeof AppTransactionsTransactionIdRouteImport
      parentRoute: typeof AppTransactionsRouteRoute
    }
    '/app/sellers/new': {
      id: '/app/sellers/new'
      path: '/new'
      fullPath: '/app/sellers/new'
      preLoaderRoute: typeof AppSellersNewRouteImport
      parentRoute: typeof AppSellersRouteRoute
    }
    '/app/sellers/$sellerId': {
      id: '/app/sellers/$sellerId'
      path: '/$sellerId'
      fullPath: '/app/sellers/$sellerId'
      preLoaderRoute: typeof AppSellersSellerIdRouteImport
      parentRoute: typeof AppSellersRouteRoute
    }
    '/app/reports/simulator': {
      id: '/app/reports/simulator'
      path: '/simulator'
      fullPath: '/app/reports/simulator'
      preLoaderRoute: typeof AppReportsSimulatorRouteImport
      parentRoute: typeof AppReportsRouteRoute
    }
    '/app/reports/ai': {
      id: '/app/reports/ai'
      path: '/ai'
      fullPath: '/app/reports/ai'
      preLoaderRoute: typeof AppReportsAiRouteImport
      parentRoute: typeof AppReportsRouteRoute
    }
    '/app/properties/$propertyId': {
      id: '/app/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/app/properties/$propertyId'
      preLoaderRoute: typeof AppPropertiesPropertyIdRouteImport
      parentRoute: typeof AppPropertiesRouteRoute
    }
    '/app/leads/new': {
      id: '/app/leads/new'
      path: '/new'
      fullPath: '/app/leads/new'
      preLoaderRoute: typeof AppLeadsNewRouteImport
      parentRoute: typeof AppLeadsRouteRoute
    }
    '/app/leads/$leadId': {
      id: '/app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/app/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRouteRoute
    }
    '/app/documents/new': {
      id: '/app/documents/new'
      path: '/new'
      fullPath: '/app/documents/new'
      preLoaderRoute: typeof AppDocumentsNewRouteImport
      parentRoute: typeof AppDocumentsRouteRoute
    }
    '/app/documents/$documentId': {
      id: '/app/documents/$documentId'
      path: '/$documentId'
      fullPath: '/app/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppDocumentsRouteRoute
    }
    '/app/buyers/new': {
      id: '/app/buyers/new'
      path: '/new'
      fullPath: '/app/buyers/new'
      preLoaderRoute: typeof AppBuyersNewRouteImport
      parentRoute: typeof AppBuyersRouteRoute
    }
    '/app/buyers/$buyerId': {
      id: '/app/buyers/$buyerId'
      path: '/$buyerId'
      fullPath: '/app/buyers/$buyerId'
      preLoaderRoute: typeof AppBuyersBuyerIdRouteImport
      parentRoute: typeof AppBuyersRouteRoute
    }
  }
}

interface AppBuyersRouteRouteChildren {
  AppBuyersBuyerIdRoute: typeof AppBuyersBuyerIdRoute
  AppBuyersNewRoute: typeof AppBuyersNewRoute
  AppBuyersIndexRoute: typeof AppBuyersIndexRoute
}

const AppBuyersRouteRouteChildren: AppBuyersRouteRouteChildren = {
  AppBuyersBuyerIdRoute: AppBuyersBuyerIdRoute,
  AppBuyersNewRoute: AppBuyersNewRoute,
  AppBuyersIndexRoute: AppBuyersIndexRoute,
}

const AppBuyersRouteRouteWithChildren = AppBuyersRouteRoute._addFileChildren(
  AppBuyersRouteRouteChildren,
)

interface AppDocumentsRouteRouteChildren {
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppDocumentsNewRoute: typeof AppDocumentsNewRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppDocumentsRouteRouteChildren: AppDocumentsRouteRouteChildren = {
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppDocumentsNewRoute: AppDocumentsNewRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppDocumentsRouteRouteWithChildren =
  AppDocumentsRouteRoute._addFileChildren(AppDocumentsRouteRouteChildren)

interface AppLeadsRouteRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppLeadsNewRoute: typeof AppLeadsNewRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteRouteChildren: AppLeadsRouteRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppLeadsNewRoute: AppLeadsNewRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteRouteWithChildren = AppLeadsRouteRoute._addFileChildren(
  AppLeadsRouteRouteChildren,
)

interface AppPropertiesRouteRouteChildren {
  AppPropertiesPropertyIdRoute: typeof AppPropertiesPropertyIdRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppPropertiesRouteRouteChildren: AppPropertiesRouteRouteChildren = {
  AppPropertiesPropertyIdRoute: AppPropertiesPropertyIdRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppPropertiesRouteRouteWithChildren =
  AppPropertiesRouteRoute._addFileChildren(AppPropertiesRouteRouteChildren)

interface AppReportsRouteRouteChildren {
  AppReportsAiRoute: typeof AppReportsAiRoute
  AppReportsSimulatorRoute: typeof AppReportsSimulatorRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteRouteChildren: AppReportsRouteRouteChildren = {
  AppReportsAiRoute: AppReportsAiRoute,
  AppReportsSimulatorRoute: AppReportsSimulatorRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteRouteWithChildren = AppReportsRouteRoute._addFileChildren(
  AppReportsRouteRouteChildren,
)

interface AppSellersRouteRouteChildren {
  AppSellersSellerIdRoute: typeof AppSellersSellerIdRoute
  AppSellersNewRoute: typeof AppSellersNewRoute
  AppSellersIndexRoute: typeof AppSellersIndexRoute
}

const AppSellersRouteRouteChildren: AppSellersRouteRouteChildren = {
  AppSellersSellerIdRoute: AppSellersSellerIdRoute,
  AppSellersNewRoute: AppSellersNewRoute,
  AppSellersIndexRoute: AppSellersIndexRoute,
}

const AppSellersRouteRouteWithChildren = AppSellersRouteRoute._addFileChildren(
  AppSellersRouteRouteChildren,
)

interface AppTransactionsRouteRouteChildren {
  AppTransactionsTransactionIdRoute: typeof AppTransactionsTransactionIdRoute
  AppTransactionsNewRoute: typeof AppTransactionsNewRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
}

const AppTransactionsRouteRouteChildren: AppTransactionsRouteRouteChildren = {
  AppTransactionsTransactionIdRoute: AppTransactionsTransactionIdRoute,
  AppTransactionsNewRoute: AppTransactionsNewRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
}

const AppTransactionsRouteRouteWithChildren =
  AppTransactionsRouteRoute._addFileChildren(AppTransactionsRouteRouteChildren)

interface AppRouteChildren {
  AppBuyersRouteRoute: typeof AppBuyersRouteRouteWithChildren
  AppDocumentsRouteRoute: typeof AppDocumentsRouteRouteWithChildren
  AppLeadsRouteRoute: typeof AppLeadsRouteRouteWithChildren
  AppPropertiesRouteRoute: typeof AppPropertiesRouteRouteWithChildren
  AppReportsRouteRoute: typeof AppReportsRouteRouteWithChildren
  AppSellersRouteRoute: typeof AppSellersRouteRouteWithChildren
  AppTransactionsRouteRoute: typeof AppTransactionsRouteRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuyersRouteRoute: AppBuyersRouteRouteWithChildren,
  AppDocumentsRouteRoute: AppDocumentsRouteRouteWithChildren,
  AppLeadsRouteRoute: AppLeadsRouteRouteWithChildren,
  AppPropertiesRouteRoute: AppPropertiesRouteRouteWithChildren,
  AppReportsRouteRoute: AppReportsRouteRouteWithChildren,
  AppSellersRouteRoute: AppSellersRouteRouteWithChildren,
  AppTransactionsRouteRoute: AppTransactionsRouteRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  AppBillingRoute: AppBillingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BuyRoute: BuyRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PropertiesRoute: PropertiesRoute,
  RentRoute: RentRoute,
  SellRoute: SellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
